CorsaroCristian.MVCTP7.CRUD/Models/OrdersView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CorsaroCristian.MVCTP7.Models
{
    public class OrdersView
    {
        public int Id
        {
            get;
            set;
        }

        public decimal Freight { get; set; }

        public DateTime OrderDate { get; set; }
    }
}

CorsaroCristian.MVCTP7.CRUD/Models/TipoNormalView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CorsaroCristian.MVCTP7.CRUD.Models
{
    public class TipoNormalView
    {

        public object Damage_Relations
        {
            get; set;
        }

        public object Game_Indices { get; set; }

        public object Generation { get; set; }
    }
}

CorsaroCristian.MVCTP7.CRUD/Controllers/APIPublicaController.cs
using CorsaroCristian.MVCTP7.CRUD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CorsaroCristian.MVCTP7.CRUD.Controllers
{
    public class APIPublicaController : Controller
    {
        // GET: APIPublica
        public ActionResult Index()
        {
            TipoNormalView tipoNormal = GetNormalType().GetAwaiter().GetResult();
            return View(tipoNormal);
        }

        public async Task<TipoNormalView> GetNormalType()
        {
            using (var client = new HttpClient())
            {
                HttpResponseMessage response = null;
                client.BaseAddress = new Uri("https://pokeapi.co");
                client.DefaultRequestHeaders.Accept.Clear();
                // Agrega el header Accept: application/json para recibir la data como json  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // Hace la llamada a http://url-base-del-api/api/products/<id>
                response = await client.GetAsync("api/v2/type/1").ConfigureAwait(false);

                // Si el servicio responde correctamente
                if (response != null && response.IsSuccessStatusCode)
                {
                    // Lee el response y lo deserializa como un Product
                    return await response.Content.ReadAsAsync<TipoNormalView>();
                }
                // Sino devuelve null
                return await Task.FromResult<TipoNormalView>(null);
            }
        }
    }
}

CorsaroCristian.MVCTP7.CRUD/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorsaroCristian.MVCTP7.CRUD.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Index()
        {
            return View();
        }
    }
}

CorsaroCristian.MVCTP7.CRUD/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorsaroCristian.MVCTP7.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CorsaroCristian.MVCTP7.CRUD/Controllers/OrdersController.cs
using CorsaroCristian.MVCTP7.Models;
using CorsaroCristian.NorthwindTP4.Entidades;
using CorsaroCristian.NorthwindTP4.Logica;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorsaroCristian.MVCTP7.Controllers
{
    public class OrdersController : Controller
    {
        // GET: Orders
        OrdersLogic ordersLogic = new OrdersLogic();
        public ActionResult Index()
        {
            List<Orders> orders = ordersLogic.GetAll();
            List<OrdersView> ordersView = orders.Select(o => new OrdersView
            {
                Id = o.OrderID,
                Freight = (Decimal)o.Freight,
                OrderDate = (DateTime)o.OrderDate,
            }).ToList();
            return View(ordersView);
        }

        public ActionResult Insert()
        {
            return View("InsertOrder");
        }

        [HttpPost]
        public ActionResult Insert(OrdersView ordersView )
        {
            if (ordersView.Id != 0)
            {
                return Update(ordersView);
            }
            try
            {
                Orders orderEntity = new Orders
                {
                    Freight = ordersView.Freight,
                    OrderDate = ordersView.OrderDate,

                };
                ordersLogic.Add(orderEntity);

                return RedirectToAction("Index");
            }catch(CustomException ex)
            {
                return RedirectToAction("Index", "ErrorPersonalizado",new { mensaje = ex.Message });
            }
            catch(Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }
        } 

        public ActionResult Delete(int id)
        {
            try
            {
                ordersLogic.Delete(id);
                return RedirectToAction("Index");
            }
            catch(CustomException ex)
            {
                return RedirectToAction("Index", "ErrorPersonalizado", new {mensaje = ex.Message });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }
        }

        public ActionResult Update(OrdersView ordersView)
        {
            try
            {
                Orders orderEntity = new Orders
                {
                    OrderID = ordersView.Id,
                    Freight = ordersView.Freight,
                    OrderDate = ordersView.OrderDate,

                };
                ordersLogic.Update(orderEntity);

                return RedirectToAction("Index");
            }catch (CustomException ex)
            {
                return RedirectToAction("Index", "ErrorPersonalizado", new { mensaje = ex.Message });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

CorsaroCristian.MVCTP7.CRUD/Controllers/OrdersViewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.ModelBinding;

using System.Web.Mvc;
using CorsaroCristian.MVCTP7.Models;
//using CorsaroCristian.NorthwindTP4.Datos;

namespace CorsaroCristian.MVCTP7.CRUD.Controllers
{

    public class OrdersViewsController : ApiController
    {


        public IEnumerable<string> Get()
        {
            return new string[] { "Value1, value2"};
        }


        public string Get( int id)
        {
            return "Value";
        }

        // PUT: api/OrdersViews(5)
        public void Put(int id, [FromBody] string value)
        {

        }

        // POST: odata/OrdersViews
        public void Post([FromBody] string value)
        {

        }
        public void Delete(int id)
        {

        }

    }
}

CorsaroCristian.MVCTP7.CRUD/Controllers/OrdersWebApiController.cs
using CorsaroCristian.NorthwindTP4.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using CorsaroCristian.NorthwindTP4.Logica;

namespace CorsaroCristian.MVCTP7.CRUD.Controllers
{
    public class OrdersWebApiController : ApiController
    {
        OrdersLogic ordersLogic = new OrdersLogic();
        public IEnumerable<Orders> Get()
        {
            var listado = ordersLogic.GetAll();
            return listado;
        }
    }
}

CorsaroCristian.MVCTP7.CRUD/Views/APIPublica/Index.cshtml
@model CorsaroCristian.MVCTP7.CRUD.Models.TipoNormalView
@{
    ViewBag.Title = "Tipo Normal page";
}

<h1>    caracteristicas de tipo normal.    </h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Descripcion </th>

        </tr>
    </thead>
    <tbody>


        <tr>
            <th scope="row">Damage Relation </th>
            <td>@Model.Damage_Relations </td>
        </tr>

        <tr>
            <th scope="row">Game Indices</th>
            <td>@Model.Game_Indices </td>
        </tr>

        <tr>
            <th scope="row">Generation</th>
            <td>@Model.Generation </td>
        </tr>
    </tbody>


</table>

CorsaroCristian.MVCTP7.CRUD/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CorsaroCristian.MVCTP7.CRUD/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CorsaroCristian.MVCTP7.CRUD/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CorsaroCristian.MVCTP7.CRUD/Views/Orders/Index.cshtml
@model List<CorsaroCristian.MVCTP7.Models.OrdersView>
@{
    ViewBag.Title = "Orders page";
}

<h1>    Indice de ordenes.    </h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id order</th>
            <th scope="col">Freight order </th>
            <th scope="col">Date Order</th>
            <th scope="col">Action</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var order in Model)
        {
            <tr>
                <th scope="row">@order.Id</th>
                <td>@order.Freight </td>
                <td>@order.OrderDate</td>
                <td>@Html.ActionLink("Borrar", "Delete", new { id = order.Id }, new { onclick = "return confirm('Seguro que quiere borrar?')" })</td>
                <td>@Html.ActionLink("Modificar", "Insert", "Orders", new { id = order.Id}, new { })</td>
            </tr>
        }
    </tbody>


</table>

<div>
    @Html.ActionLink("Insertar nueva orden", "Insert", "Orders")
</div>

CorsaroCristian.MVCTP7.CRUD/Views/Orders/InsertOrder.cshtml
@model CorsaroCristian.MVCTP7.Models.OrdersView
@{
    ViewBag.Title = "Orders page";
}

<h1>Vista para insertar</h1>

@using (Html.BeginForm("Insert", "Orders", FormMethod.Post))
{
    if (@ViewContext.RouteData.Values["id"] != null)
    {
        <label> OrderId:</label>@ViewContext.RouteData.Values["id"]
        @Html.TextBoxFor(o => o.Id, new { @Value = @ViewContext.RouteData.Values["id"], @hidden="true" })
    }


    <label> Freight: </label> @Html.TextBoxFor(o => o.Freight)
    <label> OrderDate: </label> @Html.TextBoxFor(o => o.OrderDate)
    <input type="submit" class="btn btn-success" value="Guardar" />
}

CorsaroCristian.MVCTP7.CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                    <li>@Html.ActionLink("API publica", "Index", "APIPublica")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>